/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-14 11:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addHighlights_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/AIB-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Spring-Security-InMemoryDB/WEB-INF/lib/spring-webmvc-5.3.19.jar!/META-INF/spring-form.tld", Long.valueOf(1649820742000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.19.jar", Long.valueOf(1715248179803L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffrm_005fform_0026_005fmodelAttribute;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffrm_005fform_0026_005fmodelAttribute = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffrm_005fform_0026_005fmodelAttribute.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  max-width: 600px;\r\n");
      out.write("  margin: 50px auto;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0 2px 5px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("  width: calc(100% - 30px); /* Adjusted to match the container padding and margins */\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]:focus, input[type=password]:focus {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("  border: 1px solid #f1f1f1;\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit button */\r\n");
      out.write(".registerbtn {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registerbtn:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a blue text color to links */\r\n");
      out.write("a {\r\n");
      out.write("  color: dodgerblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a grey background color and center the text of the \"sign in\" section */\r\n");
      out.write(".signin {\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_frm_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_frm_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  frm:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_frm_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005ffrm_005fform_0026_005fmodelAttribute.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_frm_005fform_005f0_reused = false;
    try {
      _jspx_th_frm_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_frm_005fform_005f0.setParent(null);
      // /WEB-INF/pages/addHighlights.jsp(76,0) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_frm_005fform_005f0.setModelAttribute("highlight");
      int[] _jspx_push_body_count_frm_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_frm_005fform_005f0 = _jspx_th_frm_005fform_005f0.doStartTag();
        if (_jspx_eval_frm_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("  <div class=\"container\">\r\n");
            out.write("    <h1>Add Highlights</h1>\r\n");
            out.write("    <p>Please fill this to add highlights.</p>\r\n");
            out.write("    <hr>\r\n");
            out.write("\r\n");
            out.write("    <label for=\"type\"><b>Project Name</b></label>\r\n");
            out.write("    <input type=\"text\" placeholder=\"Enter Type\" name=\"projectName\" id=\"type\" required>\r\n");
            out.write("\r\n");
            out.write("    <label for=\"technology\"><b>Project Tech Stack</b></label>\r\n");
            out.write("    <input type=\"text\" placeholder=\"Enter technology\" name=\"projectTechStack\" id=\"technology\" required>\r\n");
            out.write("\r\n");
            out.write("   <label for=\"projecttype\"><b>Project Type</b></label>\r\n");
            out.write("    <input type=\"text\" placeholder=\"Enter project type\" name=\"projectType\" id=\"technology\" required>\r\n");
            out.write("    <hr>\r\n");
            out.write("\r\n");
            out.write("    <button type=\"submit\" class=\"registerbtn\" >Add</button>\r\n");
            out.write("  </div>\r\n");
            out.write("  \r\n");
            out.write("  \r\n");
            int evalDoAfterBody = _jspx_th_frm_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_frm_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_frm_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_frm_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_frm_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ffrm_005fform_0026_005fmodelAttribute.reuse(_jspx_th_frm_005fform_005f0);
      _jspx_th_frm_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_frm_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_frm_005fform_005f0_reused);
    }
    return false;
  }
}
